### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Gabbo1005** [aseroff/pyramid#2]
Hi I downloaded the script for streamlabs chatbot but it's now working anymore! Is it just me or the poject is now discontinued and a recent update broke it?

**Comment by aseroff** [comment]
Hi Gabbo, thanks for the note. Do you have any additional information about what isn't working (failure to install, failure to work consistently, failure to work at all, the currency amount is wrong, something else?) and what steps you took (did you enable offline and test it)?

**Comment by aseroff** [comment]
I just installed a fresh download of pyramids on my chatbot (version 1.0.2.61) and tested it and confirmed it is still working. 

If it was previously working for you but isn't anymore, ensure other chatbot scripts are working, and that your bot account is connected (they have to be connected every thirty days, and the chatbot doesn't tell you when you need to reconnect). If everything else seems fine, I would consider uninstalling (deleting it from the scripts folder on your computer) and reinstalling the script in the chatbot.

I'll keep an eye on this issue for your response. Thanks again for the report.

**Comment by Gabbo1005** [comment]
Hi I installed It from the official streamlabs chatbot discord server. I have reconnected both my streamer and bot account recently so that shouldn't be a problem. I'll try to reinstall It downloading the script from GitHub and disabling all the other scripts too see if somehow they interfere. And yes i tried offline mode but It doesn't work (i also tester It when I was live). Thank you for the fast and kind answer. I'll keep you updated!

**Comment by Gabbo1005** [comment]
Fine! I reinstalled it downloading the script from Github and it works just fine. I  didn't even had to disable other scripts I had. Resolved!

**Comment by aseroff** [comment]
Awesome, @Gabbo1005, I'm really glad to hear it! I did notice that the version in the Chatbot discord is pyramids 1.1, and this is 1.2. Having wrote it, I know that anything difference between the minor versions shouldn't be major enough to cause such a discrepancy in performance...but maybe I should have them bump their version just in case... especially after this report.

Let me know if there's anything else I can do for ya.
